### ISSUE TITLE
bigip-facts.yml fails

### ISSUE THREAD

**Issue by codygreen** [f5alliances/f5_provisioner#12]
In the documentation under section Access the Lab step 5 where it asks us to run the bigip-facts.yml file I get the following error:

_command_:
ansible-playbook bigip-facts.yml --extra-vars "private_ip=3.15.192.xxx ansible_user=student1 ansible_ssh_pass=xxxx"

_output_:
TASK [COLLECT BIG-IP FACTS] ***********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'HTTPError' object has no attribute 'headers'
fatal: [f5]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/student1/.ansible/tmp/ansible-tmp-1573670106.23-209578455364416/AnsiballZ__bigip_device_facts.py", line 102, in <module>
        _ansiballz_main()
      File "/home/student1/.ansible/tmp/ansible-tmp-1573670106.23-209578455364416/AnsiballZ__bigip_device_facts.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/student1/.ansible/tmp/ansible-tmp-1573670106.23-209578455364416/AnsiballZ__bigip_device_facts.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.network.f5._bigip_device_facts', init_globals=None, run_name='__main__', alter_sys=False)
      File "/usr/lib64/python2.7/runpy.py", line 180, in run_module
        fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/modules/network/f5/_bigip_device_facts.py", line 16266, in <module>
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/modules/network/f5/_bigip_device_facts.py", line 16259, in main
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/modules/network/f5/_bigip_device_facts.py", line 15999, in exec_module
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/modules/network/f5/_bigip_device_facts.py", line 16075, in execute_managers
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 598, in modules_provisioned
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/module_utils/network/f5/bigip.py", line 36, in api
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/module_utils/network/f5/bigip.py", line 86, in connect_via_basic_auth
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 232, in get
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 222, in send
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 163, in update_response
      File "/tmp/ansible_bigip_device_facts_payload_C_CSUP/ansible_bigip_device_facts_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 160, in get_headers
    AttributeError: 'HTTPError' object has no attribute 'headers'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Comment by codygreen** [comment]
removing the additional attributes fixed the problem.  Documentation is a little vague but this is the wrong repo for the docs.  I'll open an issue there.
